name: Train Model and Predict Sensitive Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install dependencies for Python, including distutils
      - name: Install Python distutils
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-distutils python3-venv

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the training script to create the model
      - name: Run training script
        run: |
          python train_model.py

      # Run the prediction script to predict on a file
      - name: Run prediction script
        run: |
          python predict_model.py
